MAKEFILES:=$(wildcard makefile-simboloasdfa*)

.PHONY: all clean

all:
	make all --no-print-directory -f makefile-bornas
	make all --no-print-directory -f makefile-cableado
	make all --no-print-directory -f makefile-color-code
	make all --no-print-directory -f makefile-crocodile
	make all --no-print-directory -f makefile-ohm
	make all --no-print-directory -f makefile-serie-paralelo
	make all --no-print-directory -f makefile-resistencias-serie-paralelo
	make all --no-print-directory -f makefile-simbolos


clean:
	make clean --no-print-directory -f makefile-bornas
	make clean --no-print-directory -f makefile-cableado
	make clean --no-print-directory -f makefile-color-code
	make clean --no-print-directory -f makefile-crocodile
	make clean --no-print-directory -f makefile-ohm
	make clean --no-print-directory -f makefile-serie-paralelo
	make clean --no-print-directory -f makefile-resistencias-serie-paralelo
	make clean --no-print-directory -f makefile-simbolos
