
_images/inkscape-logo.png: _images/inkscape-logo.svg
	convert.exe -density 128 $<  $@


# --------------------------------------------------------------------
# ALL FILES
#
.PHONY: all clean
all: \
	_images/inkscape-logo.png

clean:
	rm -f _images/inkscape-logo.png
