
.PHONY: all clean

all:
	make all --no-print-directory -f makefile-vistas
	make all --no-print-directory -f makefile-views
	make all --no-print-directory -f makefile-bocetos
	make all --no-print-directory -f makefile-design

clean:
	make clean --no-print-directory -f makefile-vistas
	make clean --no-print-directory -f makefile-views
	make clean --no-print-directory -f makefile-bocetos
	make clean --no-print-directory -f makefile-design

