
.PHONY: all clean

all:
	make all --no-print-directory -f makefile-circuit
	make all --no-print-directory -f makefile-bornas
	make all --no-print-directory -f makefile-cableado
	make all --no-print-directory -f makefile-bornas-crocodile
	make all --no-print-directory -f makefile-ohm
	make all --no-print-directory -f makefile-serie-paralelo
	make all --no-print-directory -f makefile-resistencias-serie-paralelo
	make all --no-print-directory -f makefile-resolver-circuitos
	make all --no-print-directory -f makefile-simbolos
	make all --no-print-directory -f makefile-symbols
	make all --no-print-directory -C componentes-motor
	make all --no-print-directory -C componentes-rele
	make all --no-print-directory -C electric-circuit
	make all --no-print-directory -C sistema-electrico-espanol

clean:
	make clean --no-print-directory -f makefile-circuit
	make clean --no-print-directory -f makefile-bornas
	make clean --no-print-directory -f makefile-cableado
	make clean --no-print-directory -f makefile-bornas-crocodile
	make clean --no-print-directory -f makefile-ohm
	make clean --no-print-directory -f makefile-serie-paralelo
	make clean --no-print-directory -f makefile-resistencias-serie-paralelo
	make clean --no-print-directory -f makefile-resolver-circuitos
	make clean --no-print-directory -f makefile-simbolos
	make clean --no-print-directory -f makefile-symbols
	make clean --no-print-directory -C componentes-motor
	make clean --no-print-directory -C componentes-rele
	make clean --no-print-directory -C electric-circuit
	make clean --no-print-directory -C sistema-electrico-espanol
