
.PHONY: all clean

all:
	make all --no-print-directory -f makefile-circuit
	make all --no-print-directory -f makefile-bornas
	make all --no-print-directory -f makefile-cableado
	make all --no-print-directory -f makefile-bornas-crocodile
	make all --no-print-directory -f makefile-ohm
	make all --no-print-directory -f makefile-serie-paralelo
	make all --no-print-directory -f makefile-resistencias-serie-paralelo
	make all --no-print-directory -f makefile-resolver-circuitos
	make all --no-print-directory -f makefile-simbolos
	make all --no-print-directory -f makefile-symbols


clean:
	make clean --no-print-directory -f makefile-circuit
	make clean --no-print-directory -f makefile-bornas
	make clean --no-print-directory -f makefile-cableado
	make clean --no-print-directory -f makefile-bornas-crocodile
	make clean --no-print-directory -f makefile-ohm
	make clean --no-print-directory -f makefile-serie-paralelo
	make clean --no-print-directory -f makefile-resistencias-serie-paralelo
	make clean --no-print-directory -f makefile-resolver-circuitos
	make clean --no-print-directory -f makefile-simbolos
	make clean --no-print-directory -f makefile-symbols

