
.PHONY: all clean

all:
	make all --no-print-directory -f makefile-images
	make all --no-print-directory -f makefile-bornas
	make all --no-print-directory -f makefile-cableado
	make all --no-print-directory -f makefile-pcb
	make all --no-print-directory -f makefile-color-code


clean:
	make clean --no-print-directory -f makefile-images
	make clean --no-print-directory -f makefile-bornas
	make clean --no-print-directory -f makefile-cableado
	make clean --no-print-directory -f makefile-pcb
	make clean --no-print-directory -f makefile-color-code
