//
// CONFIGURACIÓN DE PÁGINA
//
#set page(
  paper: "a4",
  margin: ( top: 0.8cm, bottom: 0.6cm, left: 1.5cm, right: 1.5cm )
)

#set text(
  font: "Liberation Sans",
  lang: "es",
  size: 11pt,
  hyphenate: true
)

#set par(
  justify: true
)
  
#import "_plantilla_examen.typ": *


//
// EXAMEN
// 

#cabecera(
  [3º ESO Tecnología y Digitalización],
  [Materiales plásticos]
)

#pregunta([¿De dónde proviene la principal materia prima para fabricar plásticos?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el término utilizado para describir compuestos basados en uniones de carbono?], 0.3, sep: 1fr)
#pregunta([¿Cuántos elementos simples pueden llegar a unirse en una cadena de polímeros?], 0.3, sep: 1fr)
#pregunta([¿Cómo varía la tenacidad de los plásticos?], 0.3, sep: 1fr)
#pregunta([¿Qué plástico es muy resistente a los golpes?], 0.3, sep: 1fr)
#pregunta([¿Qué densidad tienen los plásticos en comparación con la del agua?], 0.3, sep: 1fr)
#pregunta([¿Para qué se puede utilizar el Kevlar?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el término que se suele utilizar para denominar al poliestireno expandido?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plásticos son muy transparentes y se utilizan para fabricar ventanas, DVDs y faros?], 0.3, sep: 1fr)
#pregunta([¿Qué propiedad de los termoplásticos facilita la realización de soldaduras?], 0.3, sep: 1fr)
#pregunta([¿Qué significa que los plásticos sean muy maleables y extremadamente dúctiles?], 0.3, sep: 1fr)
#pregunta([¿Por qué los plásticos son utilizados como aislantes eléctricos?], 0.3, sep: 1fr)
#pregunta([¿Qué propiedad permite a los plásticos ser moldeables?], 0.3, sep: 1fr)
#pregunta([¿En qué se utilizan comúnmente los plásticos debido a su baja conductividad térmica?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una propiedad de los plásticos que facilita la fabricación de láminas muy finas?], 0.3, sep: 1fr)
#pregunta([¿Por qué muchos contenedores de sustancias químicas están hechos de plástico?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una característica ecológica de la mayoría de los plásticos?], 0.3, sep: 1fr)
#pregunta([¿Qué representan los microplásticos en términos medioambientales?], 0.3, sep: 1fr)
#pregunta([¿Qué cantidad aproximada de microplásticos se estima que ingiere una persona cada año?], 0.3, sep: 1fr)
#pregunta([¿Cómo afecta el reciclaje a las propiedades originales de los plásticos?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el porcentaje aproximado del plástico que se recolecta para su reciclaje?], 0.3, sep: 1fr)
#pregunta([¿Qué problema medioambiental causan los microplásticos en la cadena trófica?], 0.3, sep: 1fr)
#pregunta([¿Por qué se afirma que los plásticos no son biodegradables?], 0.3, sep: 1fr)
#pregunta([¿En qué tipo de productos es muy usado el Tereftalato de polietileno (PET)?], 0.3, sep: 1fr)
#pregunta([¿En qué productos se utiliza el PVC rígido?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una característica clave de los termoplásticos que permite su reutilización?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una característica del poliestireno (PS)?], 0.3, sep: 1fr)
#pregunta([¿Cómo se conoce comúnmente al poliestireno expandido?], 0.3, sep: 1fr)
#pregunta([¿A qué se refieren los símbolos de reciclaje en los termoplásticos?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plásticos tienen la propiedad de fundirse y solidificarse repetidamente?], 0.3, sep: 1fr)
#pregunta([¿Para qué se utiliza el nailon?], 0.3, sep: 1fr)


#pagebreak()


#pregunta([¿Por qué se utiliza el teflón en mecanismos?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una característica del nailon que lo hace adecuado para fabricar paracaídas?], 0.3, sep: 1fr)
#pregunta([¿Qué temperatura puede resistir el Teflón?], 0.3, sep: 1fr)
#pregunta([¿Qué aplicaciones tiene el Teflón?], 0.3, sep: 1fr)
#pregunta([¿Qué productos se fabrican con policarbonato?], 0.3, sep: 1fr)
#pregunta([¿Qué propiedad del metacrilato lo hace adecuado para fabricar fibra óptica y expositores?], 0.3, sep: 1fr)
#pregunta([¿En qué aplicaciones se utiliza el metacrilato?], 0.3, sep: 1fr)
#pregunta([¿Qué característica fundamental tienen los plásticos termoestables?], 0.3, sep: 1fr)
#pregunta([¿En qué se utiliza comúnmente la baquelita hoy en día?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el uso más conocido de la melamina?], 0.3, sep: 1fr)
#pregunta([¿Qué característica comparten la baquelita y la madera en términos de respuesta al aumento de temperatura?], 0.3, sep: 1fr)
#pregunta([¿En qué se emplea comúnmente el poliuretano?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de productos se fabrican con la resina epoxi?], 0.3, sep: 1fr)
#pregunta([¿Qué propiedad caracteriza a los plásticos elastómeros?], 0.3, sep: 1fr)
#pregunta([¿De dónde se extrae el látex natural?], 0.3, sep: 1fr)
#pregunta([¿Cómo se diferencian las siliconas del resto de los polímeros?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el PVC?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el polipropileno?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el nailon?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el teflón?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el policarbonato?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es la baquelita?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es la resina epoxi?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el poliuretano?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el látex?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el neopreno?], 0.3, sep: 1fr)


//#test_puntos_acumulados()


/*
#pregunta([¿De dónde proviene la principal materia prima para fabricar plásticos?], 0.3, sep: 1fr)
#pregunta([¿Cómo se llaman las unidades más pequeñas que forman parte de los polímeros?], 0.3, sep: 1fr)
#pregunta([¿Por qué se comparan las cadenas de polímeros con las cuentas de un collar?], 0.3, sep: 1fr)
#pregunta([¿Cómo pueden ser las cadenas de polímeros?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el término utilizado para describir compuestos basados en uniones de carbono?], 0.3, sep: 1fr)
#pregunta([¿Cuántos elementos simples pueden llegar a unirse en una cadena de polímeros?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una característica general de los plásticos en cuanto a sus propiedades mecánicas?], 0.3, sep: 1fr)
#pregunta([¿Cómo varía la tenacidad de los plásticos?], 0.3, sep: 1fr)
#pregunta([¿Qué plástico es muy resistente a los golpes?], 0.3, sep: 1fr)
#pregunta([¿Cuál es un ejemplo de plástico de altas prestaciones que soporta altas temperaturas y tiene buena resistencia mecánica?], 0.3, sep: 1fr)
#pregunta([¿Qué densidad tienen los plásticos en comparación con la del agua?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plásticos se fabrican con pompas de gas en su interior para reducir su densidad y mejorar su capacidad de aislamiento térmico?], 0.3, sep: 1fr)
#pregunta([¿Para qué se puede utilizar el Kevlar?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el término que se suele utilizar para denominar alimentos poliestireno expandido?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plásticos son muy transparentes y se utilizan para fabricar ventanas, DVDs y faros?], 0.3, sep: 1fr)
#pregunta([¿Cómo se degradan algunos plásticos desechados en el medio ambiente?], 0.3, sep: 1fr)
#pregunta([¿Qué propiedad de los termoplásticos facilita la realización de soldaduras?], 0.3, sep: 1fr)
#pregunta([¿Qué significa que los plásticos sean muy maleables y extremadamente dúctiles?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una aplicación común de plásticos transparentes como el metacrilato?], 0.3, sep: 1fr)
#pregunta([¿Por qué los plásticos son utilizados como aislantes eléctricos?], 0.3, sep: 1fr)
#pregunta([¿Qué propiedad permite a los plásticos ser moldeables?], 0.3, sep: 1fr)
#pregunta([¿En qué se utilizan comúnmente los plásticos debido a su baja conductividad térmica?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una propiedad de los plásticos que facilita la fabricación de láminas muy finas?], 0.3, sep: 1fr)
#pregunta([¿Por qué muchos contenedores de sustancias químicas están hechos de plástico?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una característica ecológica de la mayoría de los plásticos?], 0.3, sep: 1fr)
#pregunta([¿Qué representan los microplásticos en términos medioambientales?], 0.3, sep: 1fr)
#pregunta([¿Qué cantidad aproximada de microplásticos se estima que ingiere una persona cada año según el texto?], 0.3, sep: 1fr)
#pregunta([¿Cómo afecta el reciclaje a las propiedades originales de los plásticos?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el porcentaje aproximado del plástico que se recolecta para su reciclaje?], 0.3, sep: 1fr)
#pregunta([¿Qué problema medioambiental causan los microplásticos en la cadena trófica?], 0.3, sep: 1fr)
#pregunta([¿Por qué se afirma que los plásticos no son biodegradables?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una característica principal de los termoplásticos?], 0.3, sep: 1fr)
#pregunta([¿En qué tipo de productos es muy usado el Tereftalato de polietileno (PET)?], 0.3, sep: 1fr)
#pregunta([¿Por qué el polietileno es uno de los plásticos más comunes?], 0.3, sep: 1fr)
#pregunta([¿En qué productos se utiliza el PVC rígido?], 0.3, sep: 1fr)
#pregunta([¿Cuáles son los dos grandes tipos de polietileno?], 0.3, sep: 1fr)
#pregunta([¿En qué productos se utiliza el PVC flexible?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una característica clave de los termoplásticos que permite su reutilización?], 0.3, sep: 1fr)
#pregunta([Después del Polietileno, ¿cuál es el plástico más utilizado?], 0.3, sep: 1fr)
#pregunta([¿Para qué se utiliza comúnmente el polipropileno (PP)?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una característica del poliestireno (PS)?], 0.3, sep: 1fr)
#pregunta([¿En qué productos se utiliza el poliestireno (PS)?], 0.3, sep: 1fr)
#pregunta([¿Cómo se conoce comúnmente al poliestireno expandido?], 0.3, sep: 1fr)
#pregunta([¿A qué se refieren los símbolos de reciclaje en los termoplásticos?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plásticos tienen la propiedad de fundirse y solidificarse repetidamente?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el plástico con un número 1 en su símbolo de reciclaje?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el plástico con un número 2 en su símbolo de reciclaje?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el plástico con un número 3 en su símbolo de reciclaje?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el plástico con un número 4 en su símbolo de reciclaje?], 0.3, sep: 1fr)
#pregunta([¿Cómo son los termoplásticos de altas prestaciones?], 0.3, sep: 1fr)
#pregunta([¿Para qué se utiliza el nailon?], 0.3, sep: 1fr)
#pregunta([¿Qué propiedad del teflón lo hace prácticamente inerte y antiadherente?], 0.3, sep: 1fr)
#pregunta([], 0.3, sep: 1fr)
#pregunta([¿Por qué se utiliza el teflón en mecanismos?], 0.3, sep: 1fr)
#pregunta([¿Cuál es una característica del nailon que lo hace adecuado para fabricar paracaídas?], 0.3, sep: 1fr)
#pregunta([¿Qué temperatura puede resistir el teflón?], 0.3, sep: 1fr)
#pregunta([¿Qué aplicaciones tiene el Teflón?], 0.3, sep: 1fr)
#pregunta([¿Cómo es el policarbonato?], 0.3, sep: 1fr)
#pregunta([¿Para qué se utiliza el policarbonato?], 0.3, sep: 1fr)
#pregunta([¿Qué productos se fabrican con policarbonato?], 0.3, sep: 1fr)
#pregunta([¿Cómo es el metacrilato?], 0.3, sep: 1fr)
#pregunta([¿En comparación con el vidrio, cuántas veces más resistente al impacto es el metacrilato?], 0.3, sep: 1fr)
#pregunta([¿Qué propiedad del metacrilato lo hace adecuado para fabricar fibra óptica y expositores?], 0.3, sep: 1fr)
#pregunta([¿En qué aplicaciones se utiliza el metacrilato?], 0.3, sep: 1fr)
#pregunta([¿Qué propiedad del metacrilato le permite resistir a la intemperie?], 0.3, sep: 1fr)
#pregunta([¿Qué característica fundamental tienen los plásticos termoestables?], 0.3, sep: 1fr)
#pregunta([¿Qué material fue el primer plástico sintético, creado en 1907?], 0.3, sep: 1fr)
#pregunta([¿Cómo puede moldearse la baquelita?], 0.3, sep: 1fr)
#pregunta([¿En qué se utiliza comúnmente la baquelita hoy en día?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el uso más conocido de la melamina?], 0.3, sep: 1fr)
#pregunta([¿Qué característica comparten la baquelita y la madera en términos de respuesta al aumento de temperatura?], 0.3, sep: 1fr)
#pregunta([¿Qué proceso permite a la baquelita moldearse a medida que se endurece al solidificarse?], 0.3, sep: 1fr)
#pregunta([¿Para qué se utiliza la resina epoxi?], 0.3, sep: 1fr)
#pregunta([¿En qué se emplea comúnmente el poliuretano?], 0.3, sep: 1fr)
#pregunta([¿Cuál es uno de los usos frecuentes de la resina epoxi?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de productos se fabrican con la resina epoxi?], 0.3, sep: 1fr)
#pregunta([¿Qué propiedad caracteriza a los plásticos elastómeros?], 0.3, sep: 1fr)
#pregunta([¿De dónde se extrae el látex natural?], 0.3, sep: 1fr)
#pregunta([¿En qué productos se utiliza el látex?], 0.3, sep: 1fr)
#pregunta([¿Cuál es el uso más conocido del neopreno?], 0.3, sep: 1fr)
#pregunta([¿Cómo se diferencian las siliconas del resto de los polímeros?], 0.3, sep: 1fr)
#pregunta([¿Cuál es un uso destacado de las siliconas?], 0.3, sep: 1fr)
#pregunta([¿Qué caracteriza al látex en términos de origen?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el PET?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el polietileno?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el PVC?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el polipropileno?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el poliestireno?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el nailon?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el teflón?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el policarbonato?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el metacrilato?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es la baquelita?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es la melamina?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es la resina epoxi?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el poliuretano?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el látex?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es el neopreno?], 0.3, sep: 1fr)
#pregunta([¿Qué tipo de plástico es la silicona?], 0.3, sep: 1fr)
*/